### ISSUE TITLE
webpack support

### ISSUE THREAD

**Issue by wendellmva** [jden/objectid#7]
You said the objectid has no dependency, in the package.json I see a dependecy on "bson": "^0.1.9" webpack stumbles and crashes over this. Any ideas how to solve this?

**Comment by junosuarez** [comment]
The 1.x versions of this module do not depend on mongodb and are suitable
for, eg, generating objectid strings. We took mongodb as a dependency in
2.x due to a serialization error in mongo 2.4 that was causing nasty,
silent failures on write. by using mongodb's own objectid class for
serialization, we avoided that error. It might be possible to refactor to
depend directly on the seperate bson module.
